'use client'

import { useState } from 'react'
import { Download, FileText, FileSpreadsheet, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuLabel,
} from '@/components/ui/dropdown-menu'
import { ParsedSheetRow } from '@/lib/types'
import { getSLATargets, calculateHealthScore } from '@/lib/preferences'

interface ReportDownloadProps {
  data: ParsedSheetRow[]
  headers: string[]
}

export function ReportDownload({ data, headers }: ReportDownloadProps) {
  const [generating, setGenerating] = useState(false)

  const generateCSV = () => {
    const csvHeaders = [...headers, 'Health Score', 'Grade']
    const slaTargets = getSLATargets()
    
    const rows = data.map(row => {
      const healthScore = calculateHealthScore(row.daysOut, row.hasError, slaTargets)
      return [
        ...headers.map(h => row.raw[h] || ''),
        healthScore.score.toString(),
        healthScore.grade,
      ]
    })
    
    const csv = [csvHeaders, ...rows]
      .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','))
      .join('\n')
    
    downloadFile(csv, 'availability-report.csv', 'text/csv')
  }

  const generateSummaryReport = () => {
    setGenerating(true)
    
    const slaTargets = getSLATargets()
    const withDaysOut = data.filter(r => r.daysOut !== null)
    const sortedByDays = [...withDaysOut].sort((a, b) => a.daysOut! - b.daysOut!)
    
    const stats = {
      total: data.length,
      withData: withDaysOut.length,
      errors: data.filter(r => r.hasError).length,
      avgDaysOut: withDaysOut.length > 0 
        ? (withDaysOut.reduce((s, r) => s + r.daysOut!, 0) / withDaysOut.length).toFixed(1)
        : 'N/A',
      excellent: withDaysOut.filter(r => r.daysOut! <= slaTargets.excellent).length,
      good: withDaysOut.filter(r => r.daysOut! > slaTargets.excellent && r.daysOut! <= slaTargets.good).length,
      acceptable: withDaysOut.filter(r => r.daysOut! > slaTargets.good && r.daysOut! <= slaTargets.acceptable).length,
      needsAttention: withDaysOut.filter(r => r.daysOut! > slaTargets.acceptable).length,
      best5: sortedByDays.slice(0, 5),
      worst5: sortedByDays.slice(-5).reverse(),
    }
    
    const today = new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })
    
    const report = `
ONCEHUB AVAILABILITY REPORT
Generated: ${today}
================================================================================

SUMMARY
-------
Total Links: ${stats.total}
Links with Data: ${stats.withData}
Links with Errors: ${stats.errors}
Average Wait Time: ${stats.avgDaysOut} days

SLA COMPLIANCE (Based on your configured targets)
-------------------------------------------------
Excellent (≤${slaTargets.excellent}d): ${stats.excellent} links (${((stats.excellent / stats.withData) * 100).toFixed(1)}%)
Good (≤${slaTargets.good}d): ${stats.good} links (${((stats.good / stats.withData) * 100).toFixed(1)}%)
Acceptable (≤${slaTargets.acceptable}d): ${stats.acceptable} links (${((stats.acceptable / stats.withData) * 100).toFixed(1)}%)
Needs Attention (>${slaTargets.acceptable}d): ${stats.needsAttention} links (${((stats.needsAttention / stats.withData) * 100).toFixed(1)}%)

TOP 5 BEST PERFORMERS (Shortest Wait Times)
-------------------------------------------
${stats.best5.map((r, i) => 
  `${i + 1}. ${r.raw['Name'] || 'Unknown'} - ${r.daysOut}d (${r.raw['Location'] || 'Unknown'})`
).join('\n')}

TOP 5 NEEDS ATTENTION (Longest Wait Times)
------------------------------------------
${stats.worst5.map((r, i) => 
  `${i + 1}. ${r.raw['Name'] || 'Unknown'} - ${r.daysOut}d (${r.raw['Location'] || 'Unknown'})`
).join('\n')}

${stats.errors > 0 ? `
LINKS WITH ERRORS (${stats.errors})
-----------------------------------
${data.filter(r => r.hasError).slice(0, 20).map(r => 
  `- ${r.raw['Name'] || 'Unknown'}: ${r.raw['Error Details'] || r.raw['Error Code'] || 'Unknown error'}`
).join('\n')}
${stats.errors > 20 ? `\n... and ${stats.errors - 20} more` : ''}
` : ''}

================================================================================
Report generated by Oncehub Availability Report Dashboard
`
    
    downloadFile(report.trim(), 'availability-summary.txt', 'text/plain')
    setGenerating(false)
  }

  const generateDetailedCSV = () => {
    const slaTargets = getSLATargets()
    
    const csvHeaders = [
      'Name',
      'Location', 
      'Category',
      'Category Type',
      'Days Out',
      'Health Score',
      'Grade',
      'SLA Status',
      'Has Error',
      'Error Details',
      'URL',
      'Scraped At',
    ]
    
    const rows = data.map(row => {
      const healthScore = calculateHealthScore(row.daysOut, row.hasError, slaTargets)
      let slaStatus = 'Unknown'
      if (row.daysOut !== null) {
        if (row.daysOut <= slaTargets.excellent) slaStatus = 'Excellent'
        else if (row.daysOut <= slaTargets.good) slaStatus = 'Good'
        else if (row.daysOut <= slaTargets.acceptable) slaStatus = 'Acceptable'
        else slaStatus = 'Needs Attention'
      }
      
      return [
        row.raw['Name'] || '',
        row.raw['Location'] || '',
        row.raw['Category'] || '',
        row.categoryType,
        row.daysOut?.toString() || '',
        healthScore.score.toString(),
        healthScore.grade,
        slaStatus,
        row.hasError ? 'Yes' : 'No',
        row.raw['Error Details'] || row.raw['Error Code'] || '',
        row.raw['URL'] || '',
        row.scrapedAt?.toISOString() || '',
      ]
    })
    
    const csv = [csvHeaders, ...rows]
      .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','))
      .join('\n')
    
    downloadFile(csv, 'availability-detailed.csv', 'text/csv')
  }

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          {generating ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Download className="h-4 w-4" />
          )}
          Download Report
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuLabel>Report Type</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={generateSummaryReport} className="cursor-pointer">
          <FileText className="h-4 w-4 mr-2" />
          Summary Report (.txt)
        </DropdownMenuItem>
        <DropdownMenuItem onClick={generateCSV} className="cursor-pointer">
          <FileSpreadsheet className="h-4 w-4 mr-2" />
          Basic CSV Export
        </DropdownMenuItem>
        <DropdownMenuItem onClick={generateDetailedCSV} className="cursor-pointer">
          <FileSpreadsheet className="h-4 w-4 mr-2" />
          Detailed CSV (with scores)
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}


